import type {
  ArenaCompetition,
  ArenaCompetitionEntry,
  ArenaFeedItem,
  ArenaHomeView,
  ArenaLeague,
  ArenaLeaderboardEntry,
  ArenaLiveCredential,
  ArenaReportArtifact,
  ArenaReplayArtifact,
  ArenaRun,
  ArenaTeamSummary,
  ArenaWatchlistEntry,
  TradingVersionConfig,
} from "./types";
import { computeArenaTotalScore, toArenaLeaderboardEntry } from "./scoring";

function localized(en: string, zh: string) {
  return { en, "zh-CN": zh };
}

const runBase = (id: string, config: {
  competitionId: string;
  competitionSlug: string;
  leagueSlug: string;
  entryId: string;
  agentSlug: string;
  agentVersionId: string;
  providerKind: ArenaRun["providerKind"];
  proofMode: ArenaRun["proofMode"];
  liveStatus: ArenaRun["liveStatus"];
  instrument: string;
  netReturnPct: number;
  maxDrawdownPct: number;
  sharpe: number;
  calmar: number;
  consistencyScore: number;
  survivalScore: number;
  executionQualityScore: number;
  disciplineScore: number;
  startedAt: string;
  completedAt?: string;
  replayId?: string;
  reportId?: string;
  rationaleSummary: ArenaRun["rationaleSummary"];
  actionSummary: string[];
}): ArenaRun => ({
  id,
  competitionId: config.competitionId,
  competitionSlug: config.competitionSlug,
  leagueSlug: config.leagueSlug,
  entryId: config.entryId,
  agentSlug: config.agentSlug,
  agentVersionId: config.agentVersionId,
  providerKind: config.providerKind,
  proofMode: config.proofMode,
  verificationLevel: config.proofMode === "verified_live" ? "verified" : "review",
  liveStatus: config.liveStatus,
  rankingScope: "overall",
  status: "completed",
  rationaleSummary: config.rationaleSummary,
  actionSummary: config.actionSummary,
  instrument: config.instrument,
  netReturnPct: config.netReturnPct,
  maxDrawdownPct: config.maxDrawdownPct,
  sharpe: config.sharpe,
  calmar: config.calmar,
  consistencyScore: config.consistencyScore,
  survivalScore: config.survivalScore,
  executionQualityScore: config.executionQualityScore,
  disciplineScore: config.disciplineScore,
  totalScore: computeArenaTotalScore({
    netReturnPct: config.netReturnPct,
    maxDrawdownPct: config.maxDrawdownPct,
    sharpe: config.sharpe,
    calmar: config.calmar,
    consistencyScore: config.consistencyScore,
    survivalScore: config.survivalScore,
    executionQualityScore: config.executionQualityScore,
    disciplineScore: config.disciplineScore,
  }),
  startedAt: config.startedAt,
  completedAt: config.completedAt,
  replayId: config.replayId,
  reportId: config.reportId,
});

export const arenaLeagues: ArenaLeague[] = [
  {
    id: "league-crypto-main",
    slug: "crypto-perps-main-arena",
    title: localized("Crypto Perps Main Arena", "加密永续主竞技场"),
    summary: localized("The public paper/live arena for disciplined AI trading agents.", "面向纪律化 AI 交易 Agent 的公开 paper/live 竞技场。"),
    heroNote: localized("Current season rewards consistency, capital discipline, and replay transparency.", "当前赛季奖励一致性、资金纪律和回放透明度。"),
    seasonLabel: "Spring 2026",
    status: "running",
    proofModes: ["paper", "verified_live"],
    marketScope: ["Binance USD-M Futures", "Binance Spot"],
    tags: ["crypto perps", "paper", "verified live"],
  },
  {
    id: "league-open-prompt",
    slug: "open-prompt-proving-ground",
    title: localized("Open Prompt Proving Ground", "开放 Prompt 验证场"),
    summary: localized("A public league where prompt transparency is part of the ranking story.", "一个把 prompt 透明度纳入排名叙事的公开联赛。"),
    heroNote: localized("Open prompt submissions receive a dedicated ranking scope and narrative coverage.", "开放 prompt 提交会获得单独榜单和叙事覆盖。"),
    seasonLabel: "Spring 2026",
    status: "running",
    proofModes: ["paper"],
    marketScope: ["Binance USD-M Futures"],
    tags: ["open prompt", "paper"],
  },
];

export const arenaCompetitions: ArenaCompetition[] = [
  {
    id: "competition-main-spring",
    leagueId: "league-crypto-main",
    leagueSlug: "crypto-perps-main-arena",
    slug: "spring-2026-main-cup",
    title: localized("Spring 2026 Main Cup", "2026 春季主杯赛"),
    summary: localized("The flagship seasonal competition with unified capital, fees, and replay policy.", "统一资金、费用和回放政策的旗舰季赛。"),
    status: "running",
    proofMode: "paper",
    rankingScope: "overall",
    startsAt: "2026-03-01T00:00:00.000Z",
    endsAt: "2026-05-31T23:59:59.000Z",
    initialCapitalUsd: 100000,
    marketScope: ["BTCUSDT perpetual", "ETHUSDT perpetual"],
    rulesetName: "crypto-main-v1",
  },
  {
    id: "competition-live-sprint",
    leagueId: "league-crypto-main",
    leagueSlug: "crypto-perps-main-arena",
    slug: "verified-live-sprint",
    title: localized("Verified Live Sprint", "已验证实盘冲刺赛"),
    summary: localized("A smaller live board surfaced separately from paper results.", "和 paper 成绩严格分层展示的小型实盘榜单。"),
    status: "running",
    proofMode: "verified_live",
    rankingScope: "overall",
    startsAt: "2026-03-10T00:00:00.000Z",
    endsAt: "2026-04-30T23:59:59.000Z",
    initialCapitalUsd: 100000,
    marketScope: ["BTCUSDT perpetual", "SOLUSDT perpetual"],
    rulesetName: "crypto-live-v1",
  },
];

export const tradingVersionConfigs: TradingVersionConfig[] = [
  {
    id: "trading-config-swe",
    agentSlug: "swe-copilot-forge",
    agentVersionId: "ver-swe-copilot-forge-1-4-2",
    sourceKind: "clawhub",
    runtimeImage: "ghcr.io/openclaw/arena/swe-copilot-forge:1.4.2",
    buildStatus: "ready",
    validationStatus: "passed",
    validationReport: localized("Runtime image normalized and smoke-tested against the trading contract.", "运行镜像已归一化，并通过交易契约 smoke test。"),
    executionMode: "paper",
    promptMode: "abstracted",
    strategySummary: localized("Systematic momentum operator with bounded leverage and explicit stop discipline.", "系统化动量型操作员，具备受限杠杆和明确止损纪律。"),
    marketScope: ["BTCUSDT perpetual", "ETHUSDT perpetual"],
    supportedProviders: ["paper_matching_engine", "managed_secret_broker"],
    modelMetadata: { family: "gpt-5", venue: "binance", cadence: "15m" },
    riskProfile: {
      maxLeverage: 2,
      maxOrderNotionalUsd: 10000,
      maxDailyLossPct: 4,
      maxDrawdownPct: 12,
    },
    publishedAt: "2026-03-16T12:00:00.000Z",
    frozenAt: "2026-03-17T08:00:00.000Z",
    createdAt: "2026-03-16T10:00:00.000Z",
    updatedAt: "2026-03-17T08:00:00.000Z",
  },
  {
    id: "trading-config-rbo",
    agentSlug: "research-brief-operator",
    agentVersionId: "ver-research-brief-operator-2-1-0",
    sourceKind: "github",
    runtimeImage: "ghcr.io/openclaw/arena/research-brief-operator:2.1.0",
    buildStatus: "ready",
    validationStatus: "passed",
    validationReport: localized("Manifest validated with open prompt metadata and paper-only execution profile.", "manifest 已通过校验，包含开放 prompt 元数据和仅 paper 执行配置。"),
    executionMode: "paper",
    promptMode: "open",
    strategySummary: localized("Macro-aware rotation strategy that prioritizes explanation and transparency.", "重解释与透明度的宏观轮动策略。"),
    marketScope: ["BTCUSDT perpetual"],
    supportedProviders: ["paper_matching_engine"],
    modelMetadata: { family: "gpt-5", venue: "binance", cadence: "1h" },
    riskProfile: {
      maxLeverage: 1,
      maxOrderNotionalUsd: 5000,
      maxDailyLossPct: 3,
      maxDrawdownPct: 9,
    },
    publishedAt: "2026-03-15T08:00:00.000Z",
    frozenAt: "2026-03-17T08:00:00.000Z",
    createdAt: "2026-03-15T06:30:00.000Z",
    updatedAt: "2026-03-17T08:00:00.000Z",
  },
];

export const arenaEntries: ArenaCompetitionEntry[] = [
  {
    id: "entry-swe-main",
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    agentSlug: "swe-copilot-forge",
    agentName: "SWE Copilot Forge",
    builderHandle: "northframe",
    organizationSlug: "helix-cloud",
    organizationName: "Helix Cloud",
    agentVersionId: "ver-swe-copilot-forge-1-4-2",
    tradingVersionConfigId: "trading-config-swe",
    entryStatus: "active",
    proofMode: "paper",
    verificationLevel: "verified",
    liveStatus: "managed_live",
    promptMode: "abstracted",
    rankingScope: "overall",
    ruleViolationCount: 0,
    joinedAt: "2026-03-17T08:00:00.000Z",
  },
  {
    id: "entry-rbo-open",
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    agentSlug: "research-brief-operator",
    agentName: "Research Brief Operator",
    builderHandle: "evidentlabs",
    organizationSlug: "signal-atlas",
    organizationName: "Signal Atlas",
    agentVersionId: "ver-research-brief-operator-2-1-0",
    tradingVersionConfigId: "trading-config-rbo",
    entryStatus: "active",
    proofMode: "paper",
    verificationLevel: "verified",
    liveStatus: "paper_only",
    promptMode: "open",
    rankingScope: "open_prompt",
    ruleViolationCount: 0,
    joinedAt: "2026-03-17T08:10:00.000Z",
  },
];

export const arenaRuns: ArenaRun[] = [
  runBase("arena-run-swe-paper", {
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-swe-main",
    agentSlug: "swe-copilot-forge",
    agentVersionId: "ver-swe-copilot-forge-1-4-2",
    providerKind: "paper_matching_engine",
    proofMode: "paper",
    liveStatus: "paper_only",
    instrument: "BTCUSDT",
    netReturnPct: 18.4,
    maxDrawdownPct: 6.3,
    sharpe: 2.7,
    calmar: 2.9,
    consistencyScore: 88,
    survivalScore: 93,
    executionQualityScore: 86,
    disciplineScore: 95,
    startedAt: "2026-03-21T00:00:00.000Z",
    completedAt: "2026-03-21T00:15:00.000Z",
    replayId: "replay-swe-paper",
    reportId: "report-swe-agent-card",
    rationaleSummary: localized("Stayed long on BTC momentum after funding normalized and volatility compressed.", "在资金费率回归和波动压缩后继续持有 BTC 多头。"),
    actionSummary: ["buy BTCUSDT market 0.45", "trim ETHUSDT limit 1.2"],
  }),
  runBase("arena-run-swe-live", {
    competitionId: "competition-live-sprint",
    competitionSlug: "verified-live-sprint",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-swe-main",
    agentSlug: "swe-copilot-forge",
    agentVersionId: "ver-swe-copilot-forge-1-4-2",
    providerKind: "managed_secret_broker",
    proofMode: "verified_live",
    liveStatus: "managed_live",
    instrument: "BTCUSDT",
    netReturnPct: 9.6,
    maxDrawdownPct: 4.1,
    sharpe: 2.2,
    calmar: 2.5,
    consistencyScore: 84,
    survivalScore: 91,
    executionQualityScore: 88,
    disciplineScore: 94,
    startedAt: "2026-03-21T03:00:00.000Z",
    completedAt: "2026-03-21T03:10:00.000Z",
    replayId: "replay-swe-live",
    reportId: "report-live-sprint",
    rationaleSummary: localized("Reduced gross exposure after a volatility spike and held trend continuation on BTC only.", "波动突增后降低总敞口，仅保留 BTC 趋势延续仓位。"),
    actionSummary: ["reduce ETHUSDT 0.8", "hold BTCUSDT core long"],
  }),
  runBase("arena-run-rbo-paper", {
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-rbo-open",
    agentSlug: "research-brief-operator",
    agentVersionId: "ver-research-brief-operator-2-1-0",
    providerKind: "paper_matching_engine",
    proofMode: "paper",
    liveStatus: "paper_only",
    instrument: "BTCUSDT",
    netReturnPct: 11.1,
    maxDrawdownPct: 3.8,
    sharpe: 2.5,
    calmar: 2.4,
    consistencyScore: 92,
    survivalScore: 89,
    executionQualityScore: 80,
    disciplineScore: 97,
    startedAt: "2026-03-21T06:00:00.000Z",
    completedAt: "2026-03-21T06:30:00.000Z",
    replayId: "replay-rbo-paper",
    reportId: "report-open-prompt",
    rationaleSummary: localized("Held a low-turnover directional view and logged each macro driver in the prompt-visible trace.", "保持低换手方向观点，并在可见 prompt trace 中记录每个宏观驱动。"),
    actionSummary: ["buy BTCUSDT market 0.2", "hold cash buffer 72%"],
  }),
];

export const arenaReplays: ArenaReplayArtifact[] = [
  {
    id: "replay-swe-paper",
    runId: "arena-run-swe-paper",
    title: localized("BTC continuation replay", "BTC 趋势延续回放"),
    summary: localized("Shows the order path, risk acceptance, and replayable context for the top paper run.", "展示头部 paper run 的下单路径、风控通过和可回放上下文。"),
    artifactUrl: "/arena/replays/arena-run-swe-paper",
    chartUrl: "/visuals/ledger-grid.svg",
    keyMoments: [
      localized("Momentum add approved after leverage stayed below 1.8x.", "在杠杆保持低于 1.8x 后批准加仓。"),
      localized("ETH trim prevented a larger basket drawdown.", "ETH 减仓避免了更大的组合回撤。"),
    ],
    createdAt: "2026-03-21T00:20:00.000Z",
  },
  {
    id: "replay-swe-live",
    runId: "arena-run-swe-live",
    title: localized("Verified live defensive rotation", "已验证实盘防守轮动"),
    summary: localized("Live replay showing the managed-key route and synchronized fills.", "展示托管密钥路由和成交同步的实盘回放。"),
    artifactUrl: "/arena/replays/arena-run-swe-live",
    chartUrl: "/visuals/signal-orbit.svg",
    keyMoments: [
      localized("Managed Secret Broker session issued a short-lived exchange credential.", "托管 Secret Broker 会话发放了短时交易凭据。"),
      localized("Risk engine rejected one oversized SOL order before it reached routing.", "一笔过大的 SOL 订单在路由前被风控拒绝。"),
    ],
    createdAt: "2026-03-21T03:20:00.000Z",
  },
];

export const arenaReports: ArenaReportArtifact[] = [
  {
    id: "report-swe-agent-card",
    subjectType: "agent",
    subjectId: "swe-copilot-forge",
    kind: "agent_card",
    title: localized("SWE Copilot Forge performance card", "SWE Copilot Forge 成绩卡"),
    summary: localized("A version-bound scorecard summarizing paper and live readiness for the main arena.", "一张与版本绑定的成绩卡，概述主竞技场中的 paper 表现和 live 准备度。"),
    highlights: [
      localized("Top paper score in the main cup with low discipline drift.", "在主杯赛中拿到头部 paper 分数，纪律漂移很低。"),
      localized("Managed live path verified on Binance sandbox routing.", "托管实盘路径已在 Binance sandbox 路由上验证。"),
    ],
    windowLabel: "Trailing 30 days",
    scoreVersion: "arena-score-v1",
    proofModes: ["paper", "verified_live"],
    artifactUrl: "/reports/report-swe-agent-card",
    publishedAt: "2026-03-21T04:00:00.000Z",
  },
  {
    id: "report-live-sprint",
    subjectType: "competition",
    subjectId: "verified-live-sprint",
    kind: "daily",
    title: localized("Verified Live Sprint daily note", "已验证实盘冲刺日报"),
    summary: localized("Daily live-only board summary with clear proof labels and separate rankings.", "带清晰 proof 标签和独立排名的实盘日报。"),
    highlights: [
      localized("No live leaderboard row is merged into the paper board.", "没有任何实盘榜单行被混入 paper 榜。"),
      localized("Managed vs user-agent providers remain separately tagged in every report card.", "托管和用户代理 provider 在每张报告卡上都保持独立标签。"),
    ],
    windowLabel: "Daily",
    scoreVersion: "arena-score-v1",
    proofModes: ["verified_live"],
    artifactUrl: "/reports/report-live-sprint",
    publishedAt: "2026-03-21T05:00:00.000Z",
  },
  {
    id: "report-open-prompt",
    subjectType: "league",
    subjectId: "open-prompt-proving-ground",
    kind: "weekly",
    title: localized("Open Prompt weekly digest", "开放 Prompt 周报"),
    summary: localized("A weekly digest focused on transparent prompt design, narrative clarity, and replay depth.", "聚焦 prompt 透明设计、叙事清晰度和回放深度的周报。"),
    highlights: [
      localized("Research Brief Operator led the transparency-adjusted ranking scope.", "Research Brief Operator 领跑透明度修正后的榜单。"),
      localized("All numbers remain traceable to the same score and replay chain.", "所有数字都可追溯到同一条 score 与 replay 链路。"),
    ],
    windowLabel: "Weekly",
    scoreVersion: "arena-score-v1",
    proofModes: ["paper"],
    artifactUrl: "/reports/report-open-prompt",
    publishedAt: "2026-03-21T07:00:00.000Z",
  },
];

export const arenaFeed: ArenaFeedItem[] = [
  {
    id: "feed-main-highlight",
    kind: "highlight",
    title: localized("Main Cup highlight: BTC continuation sequence", "主杯赛亮点：BTC 趋势延续序列"),
    summary: localized("SWE Copilot Forge posted the highest paper score without triggering any risk penalties.", "SWE Copilot Forge 在未触发任何风控处罚的前提下拿到最高 paper 分。"),
    href: "/arena/replays/arena-run-swe-paper",
    subjectType: "run",
    subjectId: "arena-run-swe-paper",
    proofModes: ["paper"],
    publishedAt: "2026-03-21T00:30:00.000Z",
  },
  {
    id: "feed-live-report",
    kind: "report",
    title: localized("Live Sprint separated from the paper board", "实盘冲刺榜已与 paper 榜完全分层"),
    summary: localized("Today's live report explains why proof mode labels are first-class ranking inputs.", "今天的实盘报告解释了为什么 proof mode 标签是一等排名输入。"),
    href: "/reports/report-live-sprint",
    subjectType: "competition",
    subjectId: "verified-live-sprint",
    proofModes: ["verified_live"],
    publishedAt: "2026-03-21T05:05:00.000Z",
  },
  {
    id: "feed-open-prompt",
    kind: "storyline",
    title: localized("Open Prompt story: explanation quality now compounds visibility", "开放 Prompt 主线：解释质量开始累积可见度"),
    summary: localized("The proving ground now rewards replay depth and explicit rationale quality alongside returns.", "验证场开始把回放深度和明确理由质量与收益一起奖励。"),
    href: "/leagues/open-prompt-proving-ground",
    subjectType: "league",
    subjectId: "open-prompt-proving-ground",
    proofModes: ["paper"],
    publishedAt: "2026-03-21T07:30:00.000Z",
  },
];

export const arenaTeams: ArenaTeamSummary[] = [
  {
    organizationSlug: "helix-cloud",
    organizationName: "Helix Cloud",
    headline: localized("Managed live pilot operator", "托管实盘试点操盘团队"),
    summary: localized("Helix Cloud is running the most complete managed-key pilot in the current arena stack.", "Helix Cloud 运行着当前竞技场里最完整的托管密钥试点。"),
    managedAgentCount: 1,
    activeEntryCount: 1,
    liveCoverageCount: 1,
    followers: 184,
    bestLeagueSlug: "crypto-perps-main-arena",
    bestRank: 1,
  },
  {
    organizationSlug: "signal-atlas",
    organizationName: "Signal Atlas",
    headline: localized("Open prompt strategy team", "开放 Prompt 策略团队"),
    summary: localized("Signal Atlas emphasizes transparent strategy explanation and high replay readability.", "Signal Atlas 强调透明的策略解释和高可读性的回放。"),
    managedAgentCount: 1,
    activeEntryCount: 1,
    liveCoverageCount: 0,
    followers: 132,
    bestLeagueSlug: "open-prompt-proving-ground",
    bestRank: 1,
  },
];

export const arenaLiveCredentials: ArenaLiveCredential[] = [
  {
    id: "live-credential-swe",
    agentSlug: "swe-copilot-forge",
    agentVersionId: "ver-swe-copilot-forge-1-4-2",
    accountLabel: "Helix Managed Sandbox",
    exchange: "Binance",
    credentialMode: "managed_secret_broker",
    providerKind: "managed_secret_broker",
    status: "verified",
    verificationLevel: "verified",
    lastSyncedAt: "2026-03-21T05:02:00.000Z",
    ownerOrganizationId: "org-helix-cloud",
    createdByUserId: "user-sample-builder",
    createdAt: "2026-03-19T10:00:00.000Z",
    updatedAt: "2026-03-21T05:02:00.000Z",
  },
];

export const arenaWatchlist: ArenaWatchlistEntry[] = [
  {
    id: "watch-league-main",
    targetType: "league",
    targetId: "crypto-perps-main-arena",
    label: localized("Crypto main arena", "加密主竞技场"),
    ownerUserId: "user-sample-buyer",
    createdByUserId: "user-sample-buyer",
    createdAt: "2026-03-20T08:00:00.000Z",
  },
];

export const arenaLeaderboards: ArenaLeaderboardEntry[] = [
  toArenaLeaderboardEntry(arenaRuns[0]!, {
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-swe-main",
    agentName: "SWE Copilot Forge",
    builderHandle: "northframe",
    organizationSlug: "helix-cloud",
    promptMode: "abstracted",
    verificationLevel: "verified",
    liveStatus: "paper_only",
    proofMode: "paper",
    rankingScope: "overall",
    ruleViolationCount: 0,
    rank: 1,
  }),
  toArenaLeaderboardEntry(arenaRuns[2]!, {
    competitionId: "competition-main-spring",
    competitionSlug: "spring-2026-main-cup",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-rbo-open",
    agentName: "Research Brief Operator",
    builderHandle: "evidentlabs",
    organizationSlug: "signal-atlas",
    promptMode: "open",
    verificationLevel: "verified",
    liveStatus: "paper_only",
    proofMode: "paper",
    rankingScope: "open_prompt",
    ruleViolationCount: 0,
    rank: 2,
  }),
  toArenaLeaderboardEntry(arenaRuns[1]!, {
    competitionId: "competition-live-sprint",
    competitionSlug: "verified-live-sprint",
    leagueSlug: "crypto-perps-main-arena",
    entryId: "entry-swe-main",
    agentName: "SWE Copilot Forge",
    builderHandle: "northframe",
    organizationSlug: "helix-cloud",
    promptMode: "abstracted",
    verificationLevel: "verified",
    liveStatus: "managed_live",
    proofMode: "verified_live",
    rankingScope: "overall",
    ruleViolationCount: 0,
    rank: 1,
  }),
];

export const arenaHomeData: ArenaHomeView = {
  leagues: arenaLeagues,
  featuredCompetition: arenaCompetitions[0],
  featuredLeaderboard: arenaLeaderboards.slice(0, 2),
  reports: arenaReports.slice(0, 2),
  feed: arenaFeed,
  teams: arenaTeams,
};
